(() => {
'use strict';

const STORE_KEY='paros.fs.data.v1';
const SUBJECTS={
  maths:{label:'Maths',topics:['Number','Fractions','Decimals','Percentages','Ratio','Measures','Area & perimeter','Data & charts']},
  english:{label:'English',topics:['Reading','Writing','Spelling','Grammar','Punctuation','Speaking & listening','Purpose & audience','Formal communication']},
  digital:{label:'Digital Skills',topics:['Devices & files','Email','Documents','Spreadsheets','Online safety','Online forms','Collaboration','AI literacy']}
};
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>`${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`;
const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,Number(n)||0));
const pad=n=>String(n).padStart(2,'0');
const dateKey=(d=new Date())=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const todayKey=()=>dateKey(new Date());
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Not set';
const minsToText=m=>{m=Math.max(0,Math.round(Number(m)||0));const h=Math.floor(m/60),r=m%60;return h&&r?`${h}h ${r}m`:h?`${h}h`:`${r}m`;};
const timeToMinutes=t=>{const [h,m]=String(t||'00:00').split(':').map(Number);return (h||0)*60+(m||0);};
const nowMinutes=()=>new Date().getHours()*60+new Date().getMinutes();
const weekday=()=>new Date().toLocaleDateString('en-GB',{weekday:'long'});
const clone=v=>JSON.parse(JSON.stringify(v));

const defaultState={settings:{tutorName:'',centre:''},learners:[],classes:[],attendance:{},resources:[],selectedLearnerId:null,selectedClassId:null};
let state=load();
let currentView='';
let currentLearnerId=null;
let currentClassId=null;
let registerTicker=null;

function load(){try{const x=JSON.parse(localStorage.getItem(STORE_KEY)||'null');return x&&typeof x==='object'?{...clone(defaultState),...x,settings:{...defaultState.settings,...(x.settings||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state));updateHomeMetrics();}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function selectedLearner(){return state.learners.find(l=>l.id===currentLearnerId||l.id===state.selectedLearnerId)||null}
function selectedClass(){return state.classes.find(c=>c.id===currentClassId||c.id===state.selectedClassId)||null}
function subjectLabel(k){return SUBJECTS[k]?.label||k}
function topicDefaults(){const out={};Object.entries(SUBJECTS).forEach(([key,s])=>{out[key]={initial:null,current:null,topics:Object.fromEntries(s.topics.map(t=>[t,null]))}});return out}
function normaliseLearner(l){return {...l,skills:{...topicDefaults(),...(l.skills||{})},planHistory:Array.isArray(l.planHistory)?l.planHistory:[],assessments:Array.isArray(l.assessments)?l.assessments:[]}}
state.learners=state.learners.map(normaliseLearner);

const screen=$('#screen'),paros=$('#paros'),stage=$('#parosStage'),speech=$('#parosSpeech'),contextTitle=$('#contextTitle'),pillStack=$('#pillStack'),backButton=$('#backButton'),menuButton=$('#menuButton'),toolsMenu=$('#toolsMenu'),overlay=$('#overlayPanel'),overlayTitle=$('#overlayTitle'),overlaySubtitle=$('#overlaySubtitle'),overlayKicker=$('#overlayKicker'),overlayContent=$('#overlayContent');

function say(text){speech.textContent=text;paros.classList.add('wobble');setTimeout(()=>paros.classList.remove('wobble'),900)}
function homeGreeting(){const n=state.settings.tutorName.trim();say(n?`Hi ${n}. What are we working on?`:'Hi. What are we working on?')}
function activateHome(){screen.classList.add('active');contextTitle.textContent='Maths · English · Digital Skills';contextTitle.classList.add('has-title');renderPills();setTimeout(()=>pillStack.classList.add('ready'),180);say('What do you want to work on?');backButton.classList.add('show')}
function deactivateHome(){screen.classList.remove('active');pillStack.classList.remove('ready');contextTitle.classList.remove('has-title');contextTitle.textContent='';backButton.classList.remove('show');homeGreeting()}
function renderPills(){const items=[['Learners','learner profiles & progress','learners'],['Registers','timed attendance','register'],['Assessments','starting point & diagnostics','assessments'],['ILP & Live Focus','agreed plan + adaptive priorities','plans'],['Teaching Plans','adaptive class planning','planning'],['Resources','saved plans & activities','resources']];pillStack.innerHTML=items.map(([a,b,c])=>`<button class="pill" type="button" data-open="${c}"><strong>${a}</strong><span>${b}</span></button>`).join('')}
function blink(){paros.classList.add('blink');setTimeout(()=>paros.classList.remove('blink'),150)}
setInterval(()=>{if(Math.random()>.35)blink()},3400);

function openOverlay(title,subtitle='',kicker='PAROS'){toolsMenu.classList.remove('open');menuButton.setAttribute('aria-expanded','false');overlayTitle.textContent=title;overlaySubtitle.textContent=subtitle;overlayKicker.textContent=kicker;overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');backButton.classList.add('show');overlayContent.scrollTop=0}
function closeOverlay(){overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');overlayContent.innerHTML='';currentView='';clearInterval(registerTicker);registerTicker=null;if(screen.classList.contains('active'))backButton.classList.add('show');else backButton.classList.remove('show')}

function openView(view){currentView=view;if(view==='learners')renderLearners();else if(view==='classes')renderClasses();else if(view==='register')renderRegisters();else if(view==='assessments')renderAssessments();else if(view==='plans')renderPlans();else if(view==='planning')renderPlanning();else if(view==='resources')renderResources();else if(view==='settings')renderSettings()}

function updateHomeMetrics(){
  $('#learnerCount').textContent=state.learners.length;
  $('#classCount').textContent=state.classes.length;
  $('#todayRegisterCount').textContent=state.classes.filter(c=>classOccursToday(c)).length;
  $('#focusCount').textContent=state.learners.filter(l=>learnerFocus(normaliseLearner(l)).length).length;
}

function learnerFocus(l){
  const rows=[];
  Object.entries(l.skills||{}).forEach(([subject,data])=>{
    Object.entries(data.topics||{}).forEach(([topic,score])=>{if(score!==null&&score!==''&&Number.isFinite(Number(score)))rows.push({subject,topic,score:clamp(score)});});
    if(!rows.some(r=>r.subject===subject)&&data.current!==null&&data.current!==''&&Number.isFinite(Number(data.current)))rows.push({subject,topic:`Overall ${subjectLabel(subject)}`,score:clamp(data.current)});
  });
  return rows.sort((a,b)=>a.score-b.score).slice(0,5);
}
function scoreBand(n){n=Number(n);return n>=75?['Strong','good']:n>=55?['Developing','warn']:['Priority','weak']}
function overallSubjectScore(l,key){const data=l.skills?.[key]||{};if(data.current!==null&&data.current!==''&&Number.isFinite(Number(data.current)))return clamp(data.current);const vals=Object.values(data.topics||{}).filter(x=>x!==null&&x!==''&&Number.isFinite(Number(x))).map(Number);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function learnerSummary(l){return Object.keys(SUBJECTS).map(k=>{const n=overallSubjectScore(l,k);return `${subjectLabel(k)} ${n===null?'--':Math.round(n)+'%'}`}).join(' · ')}

function renderLearners(){
  openOverlay('Learners','Starting points, current skills, live focus and individual learning plans.');
  overlayContent.innerHTML=`<div class="button-row"><button class="primary" type="button" data-add-learner>+ Add learner</button></div><div class="section-head"><h2>${state.learners.length} learner${state.learners.length===1?'':'s'}</h2><span>Stored on this device</span></div>${state.learners.length?`<div class="list">${[...state.learners].sort((a,b)=>a.name.localeCompare(b.name)).map(l=>`<button class="list-button" type="button" data-learner="${l.id}"><span class="list-copy"><strong>${esc(l.name)}</strong><span>${esc(learnerSummary(normaliseLearner(l)))}</span></span><span class="chip">${learnerFocus(normaliseLearner(l)).length} focus</span></button>`).join('')}</div>`:`<div class="empty"><strong>No learners yet</strong><span>Add a learner to begin diagnostic tracking and adaptive planning.</span></div>`}`;
}
function learnerForm(l=null){
  const item=l?normaliseLearner(l):normaliseLearner({id:uid(),name:'',reference:'',skills:topicDefaults(),planHistory:[],assessments:[]});
  openOverlay(l?'Edit learner':'Add learner','Create the learner record and starting points.');
  overlayContent.innerHTML=`<form id="learnerForm"><div class="card"><div class="form-grid"><label class="field full"><span>Learner name</span><input name="name" value="${esc(item.name)}" required></label><label class="field full"><span>Reference / ID (optional)</span><input name="reference" value="${esc(item.reference||'')}"></label></div></div><div class="section-head"><h2>Starting points</h2><span>Initial diagnostic %</span></div><div class="card"><div class="form-grid">${Object.keys(SUBJECTS).map(k=>`<label class="field"><span>${subjectLabel(k)}</span><input type="number" min="0" max="100" name="initial-${k}" value="${item.skills[k].initial??''}" placeholder="0–100"></label>`).join('')}</div></div><div class="button-row"><button class="primary" type="submit">${l?'Save learner':'Add learner'}</button>${l?'<button class="danger" type="button" data-delete-learner>Delete</button>':''}</div></form>`;
  $('#learnerForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);item.name=String(fd.get('name')||'').trim();item.reference=String(fd.get('reference')||'').trim();Object.keys(SUBJECTS).forEach(k=>{const v=fd.get(`initial-${k}`);item.skills[k].initial=v===''?null:clamp(v);if(item.skills[k].current===null)item.skills[k].current=item.skills[k].initial});const idx=state.learners.findIndex(x=>x.id===item.id);if(idx>=0)state.learners[idx]=item;else state.learners.push(item);save();toast('Learner saved');currentLearnerId=item.id;renderLearnerDetail(item.id)});
  $('[data-delete-learner]')?.addEventListener('click',()=>{if(!confirm(`Delete ${item.name}?`))return;state.learners=state.learners.filter(x=>x.id!==item.id);state.classes.forEach(c=>c.learnerIds=(c.learnerIds||[]).filter(id=>id!==item.id));save();renderLearners();toast('Learner deleted')});
}
function renderLearnerDetail(id){
  const l=normaliseLearner(state.learners.find(x=>x.id===id));if(!l)return renderLearners();currentLearnerId=id;state.selectedLearnerId=id;save();
  openOverlay(l.name,'Current position and adaptive priorities.','LEARNER');
  const focus=learnerFocus(l);
  overlayContent.innerHTML=`<div class="metric-grid">${Object.keys(SUBJECTS).map(k=>{const n=overallSubjectScore(l,k);return `<div class="metric-card"><strong>${n===null?'--':Math.round(n)+'%'}</strong><span>${subjectLabel(k)}</span><div class="progress"><i style="--p:${n===null?0:n}%"></i></div></div>`}).join('')}</div><div class="section-head"><h2>Live learning focus</h2><span>Updates from assessments</span></div><div class="card">${focus.length?focus.map(r=>{const [label,cls]=scoreBand(r.score);return `<div class="focus-row"><div><strong>${esc(r.topic)}</strong><small>${subjectLabel(r.subject)} · ${label}</small></div><div class="focus-score">${Math.round(r.score)}%</div></div>`}).join(''):'<p>Add diagnostic or progress assessment results and Paros will identify the current priorities.</p>'}</div><div class="action-grid"><button class="action-card" type="button" data-detail="assess"><strong>Add assessment</strong><span>Update current skills and topic scores.</span></button><button class="action-card" type="button" data-detail="plan"><strong>ILP & plan history</strong><span>View the agreed plan and live recommendations.</span></button><button class="action-card" type="button" data-detail="edit"><strong>Edit learner</strong><span>Change starting points or learner details.</span></button><button class="action-card" type="button" data-detail="practice"><strong>Suggested practice</strong><span>Generate targeted tasks from current weak areas.</span></button></div>`;
  $$('[data-detail]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.detail;if(a==='assess')assessmentForm(l.id);if(a==='plan')renderLearnerPlan(l.id);if(a==='edit')learnerForm(l);if(a==='practice')renderPractice(l.id)}));
}

function renderAssessments(){
  openOverlay('Assessments','Initial diagnostics, progress checks and topic-level evidence.');
  overlayContent.innerHTML=`<div class="button-row"><button class="primary" type="button" data-new-assessment ${state.learners.length?'':'disabled'}>+ Add assessment</button></div>${state.learners.length?`<div class="list">${state.learners.map(l=>`<button class="list-button" data-assess-learner="${l.id}"><span class="list-copy"><strong>${esc(l.name)}</strong><span>${l.assessments?.length||0} assessment${(l.assessments?.length||0)===1?'':'s'} · ${esc(learnerSummary(normaliseLearner(l)))}</span></span><span class="chip">Open</span></button>`).join('')}</div>`:'<div class="empty"><strong>Add a learner first</strong><span>Assessments are attached to individual learner records.</span></div>'}`;
  $('[data-new-assessment]')?.addEventListener('click',()=>assessmentForm(state.selectedLearnerId||state.learners[0]?.id));
  $$('[data-assess-learner]').forEach(b=>b.addEventListener('click',()=>renderAssessmentHistory(b.dataset.assessLearner)));
}
function assessmentForm(learnerId){
  const l=normaliseLearner(state.learners.find(x=>x.id===learnerId)||state.learners[0]);if(!l)return renderAssessments();currentLearnerId=l.id;
  openOverlay('Add assessment',`Update ${l.name}'s current position. Scores remain traceable in assessment history.`,'ASSESSMENT');
  overlayContent.innerHTML=`<form id="assessmentForm"><div class="card"><div class="form-grid"><label class="field"><span>Date</span><input type="date" name="date" value="${todayKey()}"></label><label class="field"><span>Subject</span><select name="subject" id="assessmentSubject">${Object.keys(SUBJECTS).map(k=>`<option value="${k}">${subjectLabel(k)}</option>`).join('')}</select></label><label class="field"><span>Overall score %</span><input type="number" min="0" max="100" name="score" required></label><label class="field"><span>Assessment type</span><select name="type"><option>Diagnostic</option><option>Progress check</option><option>Mock assessment</option><option>Tutor assessment</option></select></label><label class="field full"><span>Notes</span><textarea name="notes" placeholder="What did the learner find easy or difficult?"></textarea></label></div></div><div class="section-head"><h2>Topic scores</h2><span>Optional but improves adaptive focus</span></div><div class="card" id="topicScoreFields"></div><div class="button-row"><button class="primary" type="submit">Save assessment</button></div></form>`;
  const renderTopics=()=>{const k=$('#assessmentSubject').value;$('#topicScoreFields').innerHTML=`<div class="form-grid">${SUBJECTS[k].topics.map((t,i)=>`<label class="field"><span>${esc(t)}</span><input type="number" min="0" max="100" name="topic-${i}" placeholder="0–100"></label>`).join('')}</div>`};renderTopics();$('#assessmentSubject').addEventListener('change',renderTopics);
  $('#assessmentForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),subject=String(fd.get('subject')),score=clamp(fd.get('score')),topics={};SUBJECTS[subject].topics.forEach((t,i)=>{const v=fd.get(`topic-${i}`);if(v!==''&&v!==null)topics[t]=clamp(v)});const a={id:uid(),date:String(fd.get('date')||todayKey()),subject,score,type:String(fd.get('type')||'Progress check'),notes:String(fd.get('notes')||'').trim(),topics,createdAt:new Date().toISOString()};l.assessments.unshift(a);l.skills[subject].current=score;Object.entries(topics).forEach(([t,v])=>l.skills[subject].topics[t]=v);const idx=state.learners.findIndex(x=>x.id===l.id);state.learners[idx]=l;save();toast('Assessment saved');renderLearnerDetail(l.id)});
}
function renderAssessmentHistory(id){const l=normaliseLearner(state.learners.find(x=>x.id===id));if(!l)return;openOverlay(`${l.name} · assessments`,'Every saved assessment remains in the learner history.','ASSESSMENT');overlayContent.innerHTML=`<div class="button-row"><button class="primary" data-add-one>+ Add assessment</button></div><div class="section-head"><h2>History</h2><span>${l.assessments.length}</span></div>${l.assessments.length?`<div class="list">${l.assessments.map(a=>`<div class="card"><div class="list-button" style="border:0;padding:0"><span class="list-copy"><strong>${subjectLabel(a.subject)} · ${Math.round(a.score)}%</strong><span>${esc(a.type)} · ${fmtDate(a.date)}</span></span><span class="chip ${scoreBand(a.score)[1]}">${scoreBand(a.score)[0]}</span></div>${a.notes?`<p>${esc(a.notes)}</p>`:''}</div>`).join('')}</div>`:'<div class="empty"><strong>No assessments yet</strong><span>Add a diagnostic or progress check.</span></div>'}`;$('#overlayContent [data-add-one]').addEventListener('click',()=>assessmentForm(l.id))}

function latestPlan(l){return l.planHistory?.[0]||null}
function planSuggestion(l){const focus=learnerFocus(l);if(!focus.length)return null;const top=focus.slice(0,3);return {reason:`Current assessment evidence shows the greatest need in ${top.map(x=>x.topic).join(', ')}.`,focus:top.map(x=>({subject:x.subject,topic:x.topic,score:x.score})),text:`Prioritise ${top.map(x=>x.topic).join(', ')} over the next review period while maintaining stronger areas through short retrieval practice.`}}
function renderPlans(){
  openOverlay('ILP & Live Focus','The agreed plan is versioned. Paros recommendations update without silently rewriting it.');
  overlayContent.innerHTML=state.learners.length?`<div class="list">${state.learners.map(l=>{const n=normaliseLearner(l),p=latestPlan(n),f=learnerFocus(n);return `<button class="list-button" data-plan-learner="${n.id}"><span class="list-copy"><strong>${esc(n.name)}</strong><span>${p?`Plan v${p.version} · ${fmtDate(p.date)}`:'No agreed plan yet'} · ${f.length} live priorities</span></span><span class="chip">Open</span></button>`}).join('')}</div>`:`<div class="empty"><strong>No learners yet</strong><span>Add a learner before creating an individual learning plan.</span></div>`;
  $$('[data-plan-learner]').forEach(b=>b.addEventListener('click',()=>renderLearnerPlan(b.dataset.planLearner)));
}
function renderLearnerPlan(id){
  const l=normaliseLearner(state.learners.find(x=>x.id===id));if(!l)return;currentLearnerId=id;const p=latestPlan(l),suggest=planSuggestion(l),focus=learnerFocus(l);
  openOverlay(`${l.name} · ILP`,'Agreed plan + continuously updating live learning focus.','INDIVIDUAL LEARNING PLAN');
  overlayContent.innerHTML=`<div class="card"><h2>${p?`Agreed Learning Plan · v${p.version}`:'No agreed learning plan yet'}</h2>${p?`<p><strong>Aim:</strong> ${esc(p.aim||'Not added')}</p><p><strong>Review period:</strong> ${fmtDate(p.startDate)} – ${fmtDate(p.endDate)}</p><p>${esc(p.notes||'')}</p>`:'<p>Create the first version from the learner starting point and agreed outcomes.</p>'}<div class="button-row"><button class="primary" data-new-plan>${p?'Create new version':'Create plan'}</button></div></div><div class="section-head"><h2>Live Learning Focus</h2><span>Not an overwrite</span></div><div class="card">${focus.length?focus.map(r=>`<div class="focus-row"><div><strong>${esc(r.topic)}</strong><small>${subjectLabel(r.subject)} · ${scoreBand(r.score)[0]}</small></div><div class="focus-score">${Math.round(r.score)}%</div></div>`).join(''):'<p>Paros needs assessment evidence before it can prioritise weak areas.</p>'}</div>${suggest?`<div class="suggestion"><strong>Suggested plan update</strong><p>${esc(suggest.text)}</p><p><strong>Why:</strong> ${esc(suggest.reason)}</p><div class="button-row"><button class="primary" data-accept-suggestion>Accept into new plan version</button><button class="secondary" data-edit-suggestion>Edit first</button></div></div>`:''}<div class="section-head"><h2>Plan versions</h2><span>Audit history</span></div>${l.planHistory.length?`<div class="plan-history">${l.planHistory.map(p=>`<div class="history-item"><strong>Version ${p.version} · ${fmtDate(p.date)}</strong><span>${esc(p.aim||'')}${p.reason?` · ${esc(p.reason)}`:''}</span></div>`).join('')}</div>`:'<div class="empty"><strong>No previous versions</strong><span>Every material plan change will be retained here.</span></div>'}`;
  $('[data-new-plan]').addEventListener('click',()=>planForm(l.id));
  $('[data-accept-suggestion]')?.addEventListener('click',()=>planForm(l.id,suggest));
  $('[data-edit-suggestion]')?.addEventListener('click',()=>planForm(l.id,suggest));
}
function planForm(id,suggest=null){
  const l=normaliseLearner(state.learners.find(x=>x.id===id));if(!l)return;const prev=latestPlan(l),version=(prev?.version||0)+1;
  openOverlay(`Learning Plan · v${version}`,`New version for ${l.name}. Previous versions remain unchanged.`,'ILP');
  overlayContent.innerHTML=`<form id="planForm"><div class="card"><div class="form-grid"><label class="field full"><span>Overall aim</span><textarea name="aim" required>${esc(prev?.aim||'Develop the maths, English and digital skills needed for successful apprenticeship progress and employment.')}</textarea></label><label class="field"><span>Plan starts</span><input type="date" name="startDate" value="${todayKey()}"></label><label class="field"><span>Review by</span><input type="date" name="endDate" value="${esc(prev?.endDate||'')}"></label><label class="field full"><span>Current agreed priorities</span><textarea name="notes">${esc(suggest?.text||prev?.notes||'')}</textarea></label><label class="field full"><span>Reason for this version</span><textarea name="reason">${esc(suggest?.reason||(!prev?'Initial agreed learning plan':'Progress review / plan update'))}</textarea></label></div></div><div class="button-row"><button class="primary" type="submit">Save version ${version}</button></div></form>`;
  $('#planForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);l.planHistory.unshift({id:uid(),version,date:todayKey(),startDate:String(fd.get('startDate')||''),endDate:String(fd.get('endDate')||''),aim:String(fd.get('aim')||'').trim(),notes:String(fd.get('notes')||'').trim(),reason:String(fd.get('reason')||'').trim(),createdAt:new Date().toISOString()});state.learners[state.learners.findIndex(x=>x.id===l.id)]=l;save();toast(`Plan version ${version} saved`);renderLearnerPlan(l.id)});
}
function renderPractice(id){const l=normaliseLearner(state.learners.find(x=>x.id===id));if(!l)return;const focus=learnerFocus(l).slice(0,4);openOverlay(`${l.name} · suggested practice`,'Short targeted practice based on the live learning focus.','ADAPTIVE PRACTICE');overlayContent.innerHTML=focus.length?focus.map((f,i)=>`<div class="card"><h2>${i+1}. ${esc(f.topic)}</h2><p>${subjectLabel(f.subject)} · current evidence ${Math.round(f.score)}%</p><p>${practicePrompt(f)}</p></div>`).join(''):'<div class="empty"><strong>No priorities yet</strong><span>Add topic-level assessment results first.</span></div>'}
function practicePrompt(f){if(f.subject==='maths')return `Use a short real-world task that practises ${f.topic.toLowerCase()}. Include one worked example, three guided questions and one independent problem.`;if(f.subject==='english')return `Use a short workplace text to practise ${f.topic.toLowerCase()}, followed by an explanation task and one independent response.`;return `Use a practical device-based task for ${f.topic.toLowerCase()} and finish with a short safety or accuracy check.`}

function renderClasses(){
  openOverlay('Classes','Teaching groups, timetable and register setup.');
  overlayContent.innerHTML=`<div class="button-row"><button class="primary" data-add-class>+ Add class</button></div>${state.classes.length?`<div class="section-head"><h2>${state.classes.length} class${state.classes.length===1?'':'es'}</h2><span>Timetabled</span></div><div class="list">${state.classes.map(c=>`<button class="list-button" data-class="${c.id}"><span class="list-copy"><strong>${esc(c.name)}</strong><span>${esc((c.subjects||[]).map(subjectLabel).join(' · ')||'No subject')} · ${(c.learnerIds||[]).length} learners · ${(c.weekdays||[]).join(', ')}</span></span><span class="chip">${esc(c.startTime)}–${esc(c.endTime)}</span></button>`).join('')}</div>`:'<div class="empty"><strong>No classes yet</strong><span>Create a class to generate recurring registers and adaptive class plans.</span></div>'}`;
  $('[data-add-class]').addEventListener('click',()=>classForm());$$('[data-class]').forEach(b=>b.addEventListener('click',()=>classForm(state.classes.find(c=>c.id===b.dataset.class))));
}
function classForm(existing=null){
  const c=existing?clone(existing):{id:uid(),name:'',subjects:['maths'],context:'',startDate:todayKey(),endDate:'',weekdays:[weekday()],startTime:'09:00',endTime:'16:00',breaks:[{start:'11:00',end:'11:30'},{start:'13:00',end:'14:00'}],learnerIds:[]};
  openOverlay(existing?'Edit class':'Create class','Paros uses this timetable to create the live register.','CLASS');
  overlayContent.innerHTML=`<form id="classForm"><div class="card"><div class="form-grid"><label class="field full"><span>Class name</span><input name="name" value="${esc(c.name)}" required placeholder="e.g. Level 2 Maths · Group A"></label><label class="field full"><span>Vocational context (optional)</span><input name="context" value="${esc(c.context||'')}" placeholder="e.g. Bricklaying, Carpentry, Mixed apprentices"></label><label class="field"><span>Starts</span><input type="date" name="startDate" value="${esc(c.startDate||'')}"></label><label class="field"><span>Ends</span><input type="date" name="endDate" value="${esc(c.endDate||'')}"></label><label class="field"><span>Start time</span><input type="time" name="startTime" value="${esc(c.startTime)}"></label><label class="field"><span>Finish time</span><input type="time" name="endTime" value="${esc(c.endTime)}"></label></div></div><div class="section-head"><h2>Subjects</h2><span>Select all that apply</span></div><div class="card"><div class="button-row">${Object.keys(SUBJECTS).map(k=>`<label class="weekday"><input type="checkbox" name="subject" value="${k}" ${(c.subjects||[]).includes(k)?'checked':''}><span style="padding:0 12px;width:auto">${subjectLabel(k)}</span></label>`).join('')}</div></div><div class="section-head"><h2>Repeats</h2><span>Weekly</span></div><div class="card"><div class="weekday-grid">${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(d=>`<label class="weekday"><input type="checkbox" name="weekday" value="${d}" ${(c.weekdays||[]).includes(d)?'checked':''}><span>${d.slice(0,3)}</span></label>`).join('')}</div></div><div class="section-head"><h2>Breaks</h2><span>Excluded from attendance</span></div><div class="card"><div class="form-grid"><label class="field"><span>Break 1 starts</span><input type="time" name="b1s" value="${esc(c.breaks?.[0]?.start||'')}"></label><label class="field"><span>Break 1 ends</span><input type="time" name="b1e" value="${esc(c.breaks?.[0]?.end||'')}"></label><label class="field"><span>Break 2 starts</span><input type="time" name="b2s" value="${esc(c.breaks?.[1]?.start||'')}"></label><label class="field"><span>Break 2 ends</span><input type="time" name="b2e" value="${esc(c.breaks?.[1]?.end||'')}"></label></div></div><div class="section-head"><h2>Learners</h2><span>${state.learners.length} available</span></div><div class="card">${state.learners.length?state.learners.map(l=>`<label class="list-button" style="margin-bottom:6px"><span class="list-copy"><strong>${esc(l.name)}</strong><span>${esc(l.reference||'')}</span></span><input type="checkbox" name="learner" value="${l.id}" ${(c.learnerIds||[]).includes(l.id)?'checked':''}></label>`).join(''):'<p>Add learners first, or create the class and add them later.</p>'}</div><div class="button-row"><button class="primary" type="submit">Save class</button>${existing?'<button class="danger" type="button" data-delete-class>Delete</button>':''}</div></form>`;
  $('#classForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);c.name=String(fd.get('name')||'').trim();c.context=String(fd.get('context')||'').trim();c.startDate=String(fd.get('startDate')||'');c.endDate=String(fd.get('endDate')||'');c.startTime=String(fd.get('startTime')||'09:00');c.endTime=String(fd.get('endTime')||'16:00');c.subjects=fd.getAll('subject').map(String);c.weekdays=fd.getAll('weekday').map(String);c.learnerIds=fd.getAll('learner').map(String);c.breaks=[[fd.get('b1s'),fd.get('b1e')],[fd.get('b2s'),fd.get('b2e')]].filter(x=>x[0]&&x[1]).map(x=>({start:String(x[0]),end:String(x[1])}));const idx=state.classes.findIndex(x=>x.id===c.id);if(idx>=0)state.classes[idx]=c;else state.classes.push(c);save();toast('Class saved');renderClasses()});
  $('[data-delete-class]')?.addEventListener('click',()=>{if(!confirm(`Delete ${c.name}?`))return;state.classes=state.classes.filter(x=>x.id!==c.id);save();renderClasses();toast('Class deleted')});
}

function classDateActive(c,key=todayKey()){return (!c.startDate||key>=c.startDate)&&(!c.endDate||key<=c.endDate)}
function classOccursToday(c){return classDateActive(c)&&(!c.weekdays?.length||c.weekdays.includes(weekday()))}
function registerKey(classId,key=todayKey()){return `${classId}:${key}`}
function getRegister(c,key=todayKey()){const k=registerKey(c.id,key);if(!state.attendance[k])state.attendance[k]={classId:c.id,date:key,startedAt:null,completedAt:null,records:{}};return state.attendance[k]}
function breakOverlap(c,start,end){let subtract=0;for(const b of c.breaks||[]){const bs=timeToMinutes(b.start),be=timeToMinutes(b.end);subtract+=Math.max(0,Math.min(end,be)-Math.max(start,bs))}return subtract}
function scheduledMinutes(c){const s=timeToMinutes(c.startTime),e=timeToMinutes(c.endTime);return Math.max(0,(e-s)-breakOverlap(c,s,e))}
function recordMinutes(c,r,cut=nowMinutes()){let total=0;for(const i of r.intervals||[]){const end=i.end??cut;total+=Math.max(0,end-i.start-breakOverlap(c,i.start,end))}return Math.max(0,total)}
function firstArrival(r){return (r.intervals||[])[0]?.start??null}
function registerStatus(c,r){const first=firstArrival(r);if(first===null)return 'Not arrived';const start=timeToMinutes(c.startTime);if(first>start)return `${first-start}m late`;if(first<start)return `${start-first}m early`;return 'On time'}
function autoCompleteRegisters(){let changed=false;for(const c of state.classes){if(!classOccursToday(c))continue;const reg=getRegister(c);if(reg.startedAt&&!reg.completedAt&&nowMinutes()>=timeToMinutes(c.endTime)){Object.values(reg.records).forEach(r=>{if(r.running){r.intervals[r.intervals.length-1].end=timeToMinutes(c.endTime);r.running=false}});reg.completedAt=new Date().toISOString();changed=true}}if(changed)save()}
function renderRegisters(){
  autoCompleteRegisters();openOverlay('Registers','Symi-style timed attendance: 15-minute early opening, breaks excluded, automatic finish.');
  const todays=state.classes.filter(c=>classOccursToday(c));
  overlayContent.innerHTML=todays.length?`<div class="list">${todays.map(c=>{const reg=getRegister(c),openAt=timeToMinutes(c.startTime)-15,canOpen=nowMinutes()>=openAt||reg.startedAt;return `<button class="list-button" data-register-class="${c.id}" ${canOpen?'':'disabled'}><span class="list-copy"><strong>${esc(c.name)}</strong><span>${esc(c.startTime)}–${esc(c.endTime)} · ${(c.learnerIds||[]).length} learners${!canOpen?` · opens at ${minutesClock(openAt)}`:''}</span></span><span class="chip ${reg.completedAt?'good':reg.startedAt?'warn':''}">${reg.completedAt?'Complete':reg.startedAt?'Live':'Open'}</span></button>`}).join('')}</div>`:`<div class="empty"><strong>No class scheduled today</strong><span>Create a class or add ${weekday()} to an existing class timetable.</span></div>`;
  $$('[data-register-class]').forEach(b=>b.addEventListener('click',()=>renderLiveRegister(b.dataset.registerClass)));
}
function minutesClock(m){m=(m+1440)%1440;return `${pad(Math.floor(m/60))}:${pad(m%60)}`}
function renderLiveRegister(classId){
  const c=state.classes.find(x=>x.id===classId);if(!c)return renderRegisters();currentClassId=c.id;state.selectedClassId=c.id;const reg=getRegister(c);const learners=(c.learnerIds||[]).map(id=>state.learners.find(l=>l.id===id)).filter(Boolean),expected=scheduledMinutes(c);openOverlay(c.name,`${esc(c.startTime)}–${esc(c.endTime)} · ${expected} scheduled teaching minutes excluding breaks.`,'LIVE REGISTER');
  const render=()=>{autoCompleteRegisters();const complete=!!reg.completedAt;overlayContent.innerHTML=`<div class="register-hero"><h2>${complete?'Register complete':reg.startedAt?'Register running':'Ready to start'}</h2><p>The register opens 15 minutes before the session. Learner attendance timers stop automatically at ${esc(c.endTime)}. Breaks do not count.</p><div class="register-clock">${new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</div>${!reg.startedAt?'<div class="button-row"><button class="primary" data-start-register>Start register</button></div>':!complete?'<div class="button-row"><button class="secondary" data-complete-register>Complete now</button></div>':''}</div>${learners.length?learners.map(l=>{const r=reg.records[l.id]||{intervals:[],running:false},mins=recordMinutes(c,r,complete?timeToMinutes(c.endTime):nowMinutes()),pct=expected?Math.min(100,(mins/expected)*100):0;return `<div class="register-row"><div class="register-row-head"><div><strong>${esc(l.name)}</strong><small>${registerStatus(c,r)}</small></div><span class="chip ${mins?'good':''}">${Math.round(pct)}%</span></div><div class="register-controls">${!complete?(r.running?'<button class="active" data-leave="'+l.id+'">Leave / pause</button>':'<button data-arrive="'+l.id+'">Arrived / return</button>'):''}</div><div class="register-minutes">${minsToText(mins)} attended of ${minsToText(expected)} scheduled</div></div>`}).join(''):'<div class="empty"><strong>No learners in this class</strong><span>Edit the class and add learners before taking attendance.</span></div>'}`;
    $('[data-start-register]')?.addEventListener('click',()=>{reg.startedAt=new Date().toISOString();save();render()});
    $('[data-complete-register]')?.addEventListener('click',()=>{Object.values(reg.records).forEach(r=>{if(r.running){r.intervals[r.intervals.length-1].end=nowMinutes();r.running=false}});reg.completedAt=new Date().toISOString();save();render();toast('Register completed')});
    $$('[data-arrive]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.arrive;rEnsure(reg,id);const r=reg.records[id];r.intervals.push({start:nowMinutes(),end:null});r.running=true;save();render()}));
    $$('[data-leave]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.leave;rEnsure(reg,id);const r=reg.records[id];if(r.running&&r.intervals.length)r.intervals[r.intervals.length-1].end=nowMinutes();r.running=false;save();render()}));
  };render();clearInterval(registerTicker);registerTicker=setInterval(render,30000);
}
function rEnsure(reg,id){if(!reg.records[id])reg.records[id]={intervals:[],running:false}}

function classNeeds(c){
  const learners=(c.learnerIds||[]).map(id=>state.learners.find(l=>l.id===id)).filter(Boolean).map(normaliseLearner),rows=[];
  for(const subject of (c.subjects||[])){for(const topic of SUBJECTS[subject].topics){const vals=learners.map(l=>l.skills[subject]?.topics?.[topic]).filter(v=>v!==null&&v!==''&&Number.isFinite(Number(v))).map(Number);if(vals.length)rows.push({subject,topic,average:vals.reduce((a,b)=>a+b,0)/vals.length,count:vals.length,weak:vals.filter(v=>v<55).length,strong:vals.filter(v=>v>=75).length})}}
  return rows.sort((a,b)=>a.average-b.average);
}
function renderPlanning(){
  openOverlay('Teaching Plans','Keep the planned curriculum, then adapt delivery using the current learner picture.');
  overlayContent.innerHTML=state.classes.length?`<div class="list">${state.classes.map(c=>`<button class="list-button" data-plan-class="${c.id}"><span class="list-copy"><strong>${esc(c.name)}</strong><span>${esc((c.subjects||[]).map(subjectLabel).join(' · '))} · ${(c.learnerIds||[]).length} learners</span></span><span class="chip">Plan</span></button>`).join('')}</div>`:'<div class="empty"><strong>No classes yet</strong><span>Create a class before building an adaptive teaching plan.</span></div>`;
  $$('[data-plan-class]').forEach(b=>b.addEventListener('click',()=>renderClassPlan(b.dataset.planClass)));
}
function renderClassPlan(id){
  const c=state.classes.find(x=>x.id===id);if(!c)return;currentClassId=id;const needs=classNeeds(c),priority=needs.slice(0,5),learners=(c.learnerIds||[]).map(id=>state.learners.find(l=>l.id===id)).filter(Boolean);
  openOverlay(`${c.name} · adaptive plan`,'The curriculum sequence stays visible; this layer recommends where today’s teaching should flex.','TEACHING PLAN');
  const top=priority[0];
  overlayContent.innerHTML=`<div class="card"><h2>Planned curriculum</h2><p>${esc(c.context?`${c.context} context. `:'')}Use your agreed SOW/curriculum sequence as the core plan. Paros does not silently replace it.</p></div><div class="section-head"><h2>Current class intelligence</h2><span>${learners.length} learners</span></div>${priority.length?`<div class="card">${priority.map(r=>`<div class="focus-row"><div><strong>${esc(r.topic)}</strong><small>${subjectLabel(r.subject)} · ${r.weak} need support · ${r.strong} secure</small></div><div class="focus-score">${Math.round(r.average)}%</div></div>`).join('')}</div>`:'<div class="empty"><strong>More assessment evidence needed</strong><span>Add topic scores to generate class-level adaptive recommendations.</span></div>'}${top?`<div class="section-head"><h2>Suggested adaptive lesson layer</h2><span>${esc(top.topic)}</span></div><div class="card"><h3>Core</h3><p>Teach and model ${esc(top.topic.toLowerCase())} using the planned curriculum sequence.</p><h3 style="margin-top:12px">Support</h3><p>${top.weak} learner${top.weak===1?'':'s'} currently score below 55% in this area. Use a worked example, reduced steps and guided practice before independent work.</p><h3 style="margin-top:12px">Stretch</h3><p>${top.strong} learner${top.strong===1?'':'s'} are currently secure. Give them application, explanation or error-analysis tasks rather than repeating basic questions.</p><h3 style="margin-top:12px">Context</h3><p>${contextualise(c,top)}</p><div class="button-row"><button class="primary" data-save-adaptive>Save as lesson plan</button></div></div>`:''}`;
  $('[data-save-adaptive]')?.addEventListener('click',()=>{const r={id:uid(),type:'lesson-plan',title:`${c.name} · ${top.topic}`,createdAt:new Date().toISOString(),classId:c.id,subject:top.subject,content:{topic:top.topic,average:top.average,weak:top.weak,strong:top.strong,core:`Teach and model ${top.topic}.`,support:`Guided practice for ${top.weak} learner(s) below 55%.`,stretch:`Application and explanation tasks for ${top.strong} secure learner(s).`,context:contextualise(c,top)}};state.resources.unshift(r);save();toast('Lesson plan saved');renderResources()});
}
function contextualise(c,row){const ctx=(c.context||'').toLowerCase();if(row.subject==='maths'&&/brick|mason/.test(ctx))return `Apply ${row.topic.toLowerCase()} to mortar ratios, quantities, dimensions or setting out where appropriate.`;if(row.subject==='maths'&&/carp|join/.test(ctx))return `Apply ${row.topic.toLowerCase()} to measurements, scale, cutting lists or material quantities where appropriate.`;if(row.subject==='english')return `Use a workplace instruction, method statement, email or short technical text so ${row.topic.toLowerCase()} is practised in a meaningful context.`;if(row.subject==='digital')return `Use a practical workplace task involving files, forms, email, documents or spreadsheets and finish with a security/accuracy check.`;return `Use an authentic workplace or apprenticeship example so ${row.topic.toLowerCase()} is applied rather than practised only in isolation.`}

function renderResources(){
  openOverlay('Resources','Saved adaptive lesson plans and tutor-created materials.');
  overlayContent.innerHTML=`<div class="button-row"><button class="primary" data-add-resource>+ Add resource</button></div>${state.resources.length?`<div class="section-head"><h2>Saved</h2><span>${state.resources.length}</span></div><div class="list">${state.resources.map(r=>`<button class="list-button" data-resource="${r.id}"><span class="list-copy"><strong>${esc(r.title)}</strong><span>${esc(r.type||'resource')} · ${new Date(r.createdAt).toLocaleDateString('en-GB')}</span></span><span class="chip">Open</span></button>`).join('')}</div>`:'<div class="empty"><strong>No resources saved yet</strong><span>Adaptive lesson plans can be saved here, or create a resource manually.</span></div>'}`;
  $('[data-add-resource]').addEventListener('click',resourceForm);$$('[data-resource]').forEach(b=>b.addEventListener('click',()=>renderResource(b.dataset.resource)));
}
function resourceForm(){openOverlay('Add resource','Save a tutor note, worksheet idea, quiz outline or activity.','RESOURCE');overlayContent.innerHTML=`<form id="resourceForm"><div class="card"><div class="form-grid"><label class="field full"><span>Title</span><input name="title" required></label><label class="field"><span>Type</span><select name="type"><option>Worksheet</option><option>Quiz</option><option>Activity</option><option>Mock assessment</option><option>Lesson plan</option></select></label><label class="field"><span>Subject</span><select name="subject">${Object.keys(SUBJECTS).map(k=>`<option value="${k}">${subjectLabel(k)}</option>`).join('')}</select></label><label class="field full"><span>Content / notes</span><textarea name="notes"></textarea></label></div></div><div class="button-row"><button class="primary" type="submit">Save resource</button></div></form>`;$('#resourceForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);state.resources.unshift({id:uid(),title:String(fd.get('title')||'').trim(),type:String(fd.get('type')||'Resource'),subject:String(fd.get('subject')||''),notes:String(fd.get('notes')||'').trim(),createdAt:new Date().toISOString()});save();toast('Resource saved');renderResources()})}
function renderResource(id){const r=state.resources.find(x=>x.id===id);if(!r)return;openOverlay(r.title,'Saved Paros resource.','RESOURCE');const c=r.content;overlayContent.innerHTML=`<div class="card"><h2>${esc(r.type||'Resource')}</h2><p>${r.subject?subjectLabel(r.subject):''}</p>${r.notes?`<p>${esc(r.notes)}</p>`:''}${c?`<h3 style="margin-top:12px">Core</h3><p>${esc(c.core)}</p><h3 style="margin-top:12px">Support</h3><p>${esc(c.support)}</p><h3 style="margin-top:12px">Stretch</h3><p>${esc(c.stretch)}</p><h3 style="margin-top:12px">Context</h3><p>${esc(c.context)}</p>`:''}<div class="button-row"><button class="danger" data-delete-resource>Delete</button></div></div>`;$('[data-delete-resource]').addEventListener('click',()=>{if(!confirm('Delete this resource?'))return;state.resources=state.resources.filter(x=>x.id!==id);save();renderResources();toast('Resource deleted')})}

function renderSettings(){openOverlay('Settings','Paros stays local-first. These details are stored only on this device.');overlayContent.innerHTML=`<form id="settingsForm"><div class="card"><div class="form-grid"><label class="field full"><span>Tutor name</span><input name="tutorName" value="${esc(state.settings.tutorName||'')}"></label><label class="field full"><span>Centre / provider</span><input name="centre" value="${esc(state.settings.centre||'')}"></label></div></div><div class="card"><h2>Paros</h2><p>Functional Skills tutor assistant for Maths, English and Digital Skills. Soft-purple Evia-style interface with local learner data, adaptive focus, versioned plans and timed registers.</p></div><div class="button-row"><button class="primary" type="submit">Save settings</button></div></form>`;$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);state.settings.tutorName=String(fd.get('tutorName')||'').trim();state.settings.centre=String(fd.get('centre')||'').trim();save();homeGreeting();toast('Settings saved')})}

stage.addEventListener('click',()=>screen.classList.contains('active')?deactivateHome():activateHome());stage.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();screen.classList.contains('active')?deactivateHome():activateHome()}});$('#centreMark').addEventListener('click',activateHome);
menuButton.addEventListener('click',()=>{const open=!toolsMenu.classList.contains('open');toolsMenu.classList.toggle('open',open);menuButton.setAttribute('aria-expanded',String(open))});
document.addEventListener('click',e=>{const o=e.target.closest('[data-open]');if(o){openView(o.dataset.open);return}if(!e.target.closest('#toolsMenu')&&!e.target.closest('#menuButton')){toolsMenu.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}});
$('#overlayClose').addEventListener('click',closeOverlay);
backButton.addEventListener('click',()=>{if(overlay.classList.contains('open'))closeOverlay();else if(screen.classList.contains('active'))deactivateHome()});
window.addEventListener('pageshow',()=>{autoCompleteRegisters();updateHomeMetrics()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));

updateHomeMetrics();homeGreeting();setTimeout(blink,1700);
})();
